#!/bin/bash

dir=$(dirname "$0")
pipeIN=/tmp/aplayer-pipe-in
pipeOUT=/tmp/aplayer-pipe-out

function usage() {
	echo "APlayer - Version 1.0.0"
	echo "https://github.com/Fingarde/AudioPlayer"
	echo ""
	echo "now: Get current song name"
	echo "url: Get url of current song"
	echo ""
	echo "download <url> <name>: Download a youtube player and save it to ~/Music/<name>"
	echo ""
	echo "list: Display all playlists"
	echo ""
	echo "play <playlist>: Play a playlist"
	echo "next: Skip current song"
	echo "prev: Go to previous song"
	echo "seek min:sec|time to add/remove: Move cursor in current song"
	echo "shuffle: Shuffle current playlist"
	echo ""
	echo "quit: Close aplayer"
	echo "kill: Kill all aplayer"

	exit 1
}

function createConfig() {
	printf "volume: 50" > "$dir/config"
}

function set() {
	sed -i "s/$1: .*/$1: $2/g" "$dir/config" 
}

function send() {
	lsof "$pipeIN" | grep " 5u " > /dev/null && echo "$@" > "$pipeIN"
}

function play() {
	mplayer -slave -input file="$pipeIN" -idle -playlist /tmp/.list 2> /dev/null | grep --line-buffered "Playing" > "$pipeOUT"  &
}


[ -x /usr/bin/mplayer ] || {
	echo "Missing mplayer"
	echo "apt install mplayer"
	exit 1
}

[ -x /usr/bin/ffmpeg ] || {
	echo "Missing ffmpeg"
	echo "apt install ffmpeg"
	exit 1
}

[ -x /usr/local/bin/youtube-dl ] || {
	echo "Missing mplayer"
	echo "curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl"
	echo "chmod a+rx /usr/local/bin/youtube-dl"
	exit 1
}

[ $# -eq 0 ] && usage

[ -e "$dir/config" ] || createConfig
volume=$(cat "$dir/config" | tr -d " " | grep "volume:" | cut -d ":" -f 2)

[ -e "$pipeIN" ] || mkfifo "$pipeIN"
[ -e "$pipeOUT" ] || touch "$pipeOUT"

case "$1" in
	"download")
		shift
		[ $# -lt 2 ] && usage

		youtube-dl -i -f 'bestaudio[ext=m4a]' --yes-playlist -o ~/Music/"$2"/"%(title)s-%(id)s.%(ext)s" -x "$1" | egrep -v "youtube|ffmpeg|Destination|100%|dashsegments"
		;;
	"play")
		shift 
		[ $# -eq 0 ] && usage
		
		send "quit"
		
		find $(find ~/Music -type d -iname "$1*" | head -1) -type f -regex ".*\.\(mp3\|m4a\|ogg\|flv\|opus\)" > /tmp/.list
		
		play
		;;	
	"volume")
		shift 	
		[ $# -eq 0 ] && usage

		echo "$1" | egrep "[+-]" > /dev/null && volume=$(( "$volume$1" )) || volume=$(( "$1"+1 ))
		set "volume" "$volume"

		send "volume $volume 1"
		;;
	"next")
		send "pt_step 1"
		;;	
	"prev")
		send "pt_step -1"
		;;
	"pause")	
		send "pause"
		;;
	"seek")
		shift 
		[ $# -eq 0 ] && usage

		mode="0"
		time="$1"

		echo "$1" | grep ":" > /dev/null && mode=2 && time=$(( $( echo $1 | cut -d ":" -f 1 ) * 60 + $( echo $1 | cut -d ":" -f 2 ) ))
		send "seek $time $mode"
		;;
	"quit")
		while lsof "$pipeIN" | grep " 5u " > /dev/null; do
			send "quit"
		done
		;;
	"kill")
		ps aux | grep "mplayer -slave -input file=/tmp/aplayer-pipe-in" | grep -v "grep" | tr -s " " | cut -d " " -f 2 | xargs -i kill -9 {}
		;;	
	"now")
		tail /tmp/aplayer-pipe-out | tac | head -n 1 | rev | cut -d "/" -f 1 | rev | sed "s/-.\{11\}\..\{,5\}\.//g"
		;;	
	"url")
		printf "https://www.youtube.com/watch\?v="
		tail /tmp/aplayer-pipe-out | tac | head -n 1 | rev | cut -d "/" -f 1 | rev | sed -e "s/.*-\(.\{11\}\)\..\{,5\}\./\1/g" 
		;;		
	"shuffle")
		send "quit"
	
		mv /tmp/.list /tmp/.oldlist
		cat /tmp/.oldlist | shuf > /tmp/.list

		play
		;;
	"list")
		ls ~/Music 
		;;
esac
